### CREATE USER
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Kent",
    "email": "kent@test.com"
}

### CREATE THOUGHT

POST http://localhost:3001/api/thoughts
Content-Type: application/json

{
    "thoughtText": "Test thought content",
    "userId": "6305390f4fd0051d423d23a7",
    "username": "Kent"
    
}

### UPDATE THOUGHT

PUT http://localhost:3001/api/thoughts/6305391c4fd0051d423d23a9
Content-Type: application/json

{
    "thoughtText": "Updated again test thought content"
}

### GET ALL THOUGHTS

GET http://localhost:3001/api/thoughts

### GET THOUGHT BY ID

GET http://localhost:3001/api/thoughts/6305391c4fd0051d423d23a9

### CREATE REACTION

POST http://localhost:3001/api/6305391c4fd0051d423d23a9/reactions
Content-Type: application/json

{
    "reactionBody": "AGAIN AGAIN OMG!"
}

### DELETE REACTION

DELETE http://localhost:3001/api/6305391c4fd0051d423d23a9/reactions/6305394d4fd0051d423d23b0

### DELETE THOUGHT

DELETE http://localhost:3001/api/thoughts/630150aba5531403a6c160ca

### GET ALL USERS

GET http://localhost:3001/api/users

### GET USER BY ID

GET http://localhost:3001/api/users/6305390f4fd0051d423d23a7

### UPDATE USER

PUT http://localhost:3001/api/users/6305390f4fd0051d423d23a7
Content-Type: application/json

{
    "username": "John",
    "email": "John@test.com"
}

### CREATE FRIEND

POST http://localhost:3001/api/users/6305390f4fd0051d423d23a7/friends/63014fb46baeed562f464917

### DELETE FRIEND

DELETE http://localhost:3001/api/users/6305390f4fd0051d423d23a7/friends/63014fb46baeed562f464917

### DELETE USER

DELETE http://localhost:3001/api/users/63014fb46baeed562f464917