### CREATE USER
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Charlie",
    "email": "charles@test.com"
}

### CREATE THOUGHT

POST http://localhost:3001/api/thoughts
Content-Type: application/json

{
    "thoughtText": "Test thought content",
    "userId": "63014f9d6baeed562f464915",
    "username": "Kate"
    
}

### UPDATE THOUGHT

PUT http://localhost:3001/api/thoughts/630150aba5531403a6c160ca
Content-Type: application/json

{
    "thoughtText": "Updated again test thought content"
}

### GET ALL THOUGHTS

GET http://localhost:3001/api/thoughts

### GET THOUGHT BY ID

GET http://localhost:3001/api/thoughts/63015040cac24304a22ca682

### CREATE REACTION

POST http://localhost:3001/api/63015040cac24304a22ca682/reactions
Content-Type: application/json

{
    "reactionBody": "AGAIN AGAIN OMG!"
}

### DELETE REACTION

DELETE http://localhost:3001/api/63015040cac24304a22ca682/reactions/630150f7a5531403a6c160d1

### DELETE THOUGHT

DELETE http://localhost:3001/api/thoughts/630150aba5531403a6c160ca

### GET ALL USERS

GET http://localhost:3001/api/users

### GET USER BY ID

GET http://localhost:3001/api/users/63014f9d6baeed562f464915

### UPDATE USER

PUT http://localhost:3001/api/users/63012139ca944e600d4612e7
Content-Type: application/json

{
    "username": "Kate",
    "email": "Kate@test.com"
}

### CREATE FRIEND

POST http://localhost:3001/api/users/63014f9d6baeed562f464915/friends/63014fb46baeed562f464917

### DELETE FRIEND

DELETE http://localhost:3001/api/users/63014f9d6baeed562f464915/friends/63014fb46baeed562f464917

### DELETE USER

DELETE http://localhost:3001/api/users/63012139ca944e600d4612e7